### ISSUE TITLE
review of current state (Oct 26,2016 - 3a11762)

### ISSUE THREAD

**Issue by msneddon** [kbaseapps/ReadsAPI#1]
- [x] There seems to be a lot of indentation issues (mixed tab/spaces?) in the ReadsAPI.spec file- it made things difficult to read.  That should be fixed.
- [x] To future proof this, we need to have the read parameters defined with a single WS reference string (e.g. string ref), not separate fields for id/name/workspace_name, and fetch objects based on WS reference on the backend.  This will also give us a way to specify a version. 
  https://github.com/kbaseapps/ReadsAPI/blob/master/ReadsAPI.spec#L16
- [x] To simplify things, we should just remove these unused methods from the spec.  It also produces a higher overhead when we try to update this service in the future.  (You could preserve the code somewhere, but looks like all of these have lots of duplicated code anyway, so I'm not sure it would save much)
  https://github.com/kbaseapps/ReadsAPI/blob/master/ReadsAPI.spec#L22-L84
- [x] You don't need the metadata tags- this is only for defining object specifications for the workspace
  https://github.com/kbaseapps/ReadsAPI/blob/master/ReadsAPI.spec#L120
- [x] You should clarify what happens when data is missing- are the fields simply omitted?  There are also some fields that are unclear- what does 'type' mean for instance?  Is that the WS type, or something else?
  https://github.com/kbaseapps/ReadsAPI/blob/master/ReadsAPI.spec#L169
- [ ] Your tests shouldn't rely on data already existing in the WS.  Please assume a completely empty WS in tests- so for the tests, you should create a new WS, load example data, and write tests with that example data.  You should also add some tests for data that has missing fields.  Tests failed for me I think for this reason.
  https://github.com/kbaseapps/ReadsAPI/blob/master/test/ReadsAPI_server_test.py#L78
- [ ] In general, the tests don't seem to have very good coverage- they only check that 'workspace_name', 'name', and 'id' are correct - so that only covers part of the Workspace object info, not anything in the actual object itself.
- [x] Please use get_objects2: https://github.com/kbaseapps/ReadsAPI/blob/master/lib/ReadsAPI/ReadsAPIImpl.py#L452
- [x] Lots of repeated code here:
  https://github.com/kbaseapps/ReadsAPI/blob/master/lib/ReadsAPI/ReadsAPIImpl.py#L484
  One thing you can do is define the set of fields you want to extract in a list, then iterate over that list.  Something like:

```
field_to_extract = ['read_size', ... ]
for field in fields_to_extract:
   if field in data:
     ...
```
- [ ] Since this is for the viewer, it may be fine to return everything as strings.  But as it stands now, the spec says that 'floats' are returned for many of these items, but you return empty strings.  Maybe we should switch all the fields to 'string' type in the spec, and make sure we cast everything to a string when returning.  If we don't, this may break say Java clients.
  https://github.com/kbaseapps/ReadsAPI/blob/master/lib/ReadsAPI/ReadsAPIImpl.py#L537
- [x] To make this an actual dynamic service, you need to mark it as a dynamic service in the kbase YAML file here:
  https://github.com/kbaseapps/ReadsAPI/blob/master/kbase.yml#L15
  For instance, 
  https://github.com/kbaseapps/SetAPI/blob/master/kbase.yml#L16

**Comment by realmarcin** [comment]
1. There seems to be a lot of indentation issues (mixed tab/spaces?) in the ReadsAPI.spec file- it made things difficult to read. That should be fixed.

I fixed this by removing tabs and replacing with spaces but since there is no standard requirement here (that is, the spec compilation evidently doesn't depend on whitespace) except subjective readability its hard to know what the target is... I could read the original spec with no problems ...

**Comment by realmarcin** [comment]
7  In general, the tests don't seem to have very good coverage- they only check that 'workspace_name', 'name', and 'id' are correct - so that only covers part of the Workspace object info, not anything in the actual object itself.

How are you measuring coverage? You didn't see test_get_reads_info_ok() and test_get_reads_info_all_ok()

Maybe those methods need better names, but they are returning and testing internal object data outside of metadata.

**Comment by realmarcin** [comment]
11. To make this an actual dynamic service, you need to mark it as a dynamic service in the kbase YAML file here:
https://github.com/kbaseapps/ReadsAPI/blob/master/kbase.yml#L15
For instance, 
https://github.com/kbaseapps/SetAPI/blob/master/kbase.yml#L16

easy enough, done

**Comment by realmarcin** [comment]
3 To simplify things, we should just remove these unused methods from the spec. It also produces a higher overhead when we try to update this service in the future. (You could preserve the code somewhere, but looks like all of these have lots of duplicated code anyway, so I'm not sure it would save much)
https://github.com/kbaseapps/ReadsAPI/blob/master/ReadsAPI.spec#L22-L84

I removed the platform and single_genome methods but I'm actually using get_ids for tests and get_name and get_type will be also handy... I assume we're not planning on changing WS object metadata anytime soon, since that is a deep and heavy lift. Really, these basic methods should be a part of the WS API IMHO ... If you still think these need to be removed we can discuss.

**Comment by realmarcin** [comment]
5 You should clarify what happens when data is missing- are the fields simply omitted? There are also some fields that are unclear- what does 'type' mean for instance? Is that the WS type, or something else?
https://github.com/kbaseapps/ReadsAPI/blob/master/ReadsAPI.spec#L169

Well, there was some documentation in the spec for the 'type' field? I changed to workspace_type, but I thought KBase really only had one concept of type, which was a typed object?

For the missing data I was told to return keys with empty strings -- that is done in all cases including for optional fields. So when you say 'clarfiy', what does this mean exactly?

**Comment by realmarcin** [comment]
9 Lots of repeated code here:
https://github.com/kbaseapps/ReadsAPI/blob/master/lib/ReadsAPI/ReadsAPIImpl.py#L484
One thing you can do is define the set of fields you want to extract in a list, then iterate over that list. Something like:
field_to_extract = ['read_size', ... ]
for field in fields_to_extract:
   if field in data:
     ...

Your suggestion would make the code more compact, but since I am delineating groups of fields of different class (required vs optional) and type (single vs paired) and also the fields themselves are of different types (string, int, float, map) things are a bit more complex. I'll see what I can do ...

**Comment by realmarcin** [comment]
5 You don't need the metadata tags- this is only for defining object specifications for the workspace
https://github.com/kbaseapps/ReadsAPI/blob/master/ReadsAPI.spec#L120

But each type spec corresponds to an object, so why doesn't metadata apply to this object? Because we won't have user instances of this object?

**Comment by realmarcin** [comment]
2 To future proof this, we need to have the read parameters defined with a single WS reference string (e.g. string ref), not separate fields for id/name/workspace_name, and fetch objects based on WS reference on the backend. This will also give us a way to specify a version. 
https://github.com/kbaseapps/ReadsAPI/blob/master/ReadsAPI.spec#L16

yes, but the workspace_name is a required field in the ReadsSet so better to not make extra workspace calls I think.

**Comment by msneddon** [comment]
Looks better, but still some more issues to address:
- First, tests are still failing for me.  It looks like you still have hard coded WS names in your tests (https://github.com/kbaseapps/ReadsAPI/blob/master/test/ReadsAPI_server_test.py#L78).  If those tests aren't required anymore, please remove those tests and code.  The error was:

```
ServerError: JSONRPCError: -32500. User wstester1 may not write to workspace testReadsAPI
us.kbase.workspace.exceptions.WorkspaceAuthorizationException: User wstester1 may not write to workspace testReadsAPI
```
- I don't understand your comment on point (2) - where is the workspace_name in the ReadsSet a required field?  In the SetAPI, everything is handled by references.  The widget will need to be able to get specific versions of a data object, and the canonical way to do that is by reference.  Right now it is impossible with your API to get 'get_reads_info_all' with a specific version.  So please remove the id/name/workspace_name fields and replace with one 'ref' field.  It will make your implementation code cleaner as well.
- You're still not casting these values to strings here.
  https://github.com/kbaseapps/ReadsAPI/blob/master/lib/ReadsAPI/ReadsAPIImpl.py#L458

**Comment by realmarcin** [comment]
1 I added the test data loading call to the three original basic API methods.

2 The workspace name is required for the Reads viewer. The current API has both methods to return based on obj id or name, as well as the full reference -- perhaps you didn't see those?

3 I added the cast with str(), but it didn't seem necessary -- tests passed without the cast, right?

Also, in the meantime the Reads specs version got upgraded so I upped it in the test code. Perhaps  the tests should be ignoring the object version? I can see arguments for both sides.

**Comment by msneddon** [comment]
1) Please look at this link again: https://github.com/kbaseapps/ReadsAPI/blob/master/test/ReadsAPI_server_test.py#L78  There are hard coded WS names, and when I run your tests with kb-sdk test, it tries to read those and fails.  Your tests need to create any workspaces and data that are needed in tests.

2) The WS name is passed into the reads viewer now - but that is something we are going to change, and it can always convert that to a reference for the API call.  It looks like you added some more methods that work on a single obj reference string (which is also not ideal- it should be wrapped in a parameter object, not as separate method.  And I still would strongly advise that you remove those accessory methods altogether), but I only see one version of this method: https://github.com/kbaseapps/ReadsAPI/blob/master/ReadsAPI.spec#L164  and it only accepts the parameter ReadsParams, which does not have a reference declared.  If there is another method, please send me a link to the line in the spec file (and then you should consolidate the methods if they are duplicated).

3) Looks like your tests are wrong- they need to test that the return objects are strings if that is what your spec declared.  And based on your code, if you cast to string, it looks like your current tests would in fact fail.

**Comment by realmarcin** [comment]
there is some confusion

1 is done in new code which I haven't committed yet

2 the parameter object vs separate method are different things right? you are saying that we need a method which takes a parameter object with a ref field inside? if there is a standard KBase way to do this let me know, ideally with example ;) for me a method which directly takes a ref string is the most obvious.

3 the tests assert on the entire structure so 1 vs '1' is different and would get caught (and does). you had signed off on the structure assert before but let me know if we need other testing

**Comment by realmarcin** [comment]
for 2 I still have the problem that the viewer requires the workspace name -- so I should be getting the workspace name based on the reference? that will be another workspace call, right?

**Comment by realmarcin** [comment]
anyway, I just did a push with fixes for everything but 2 pending the workspace name question

**Comment by msneddon** [comment]
Well, ok- I can't look at something if it's not committed...

I still don't know what you mean by "the viewer requires a workspace name".  The viewer is not using this API at all yet, and can easily construct a WS reference for an object to pass to this API.  We need, for a variety of reasons, to switch the viewers and apps to accept references instead of WS names and object names/ids.  You never need to get the WS name in your code- you can take the reference you get and pass it directly to the WS get_objects2 call.  So you should change this line:
https://github.com/kbaseapps/ReadsAPI/blob/master/ReadsAPI.spec#L19

to simply:

```
typedef structure {
    string ref;
} ReadsParams;
```

Also, as a general pattern we've learned, parameters should be wrapped in structures.  You can then add more parameter fields without breaking existing clients.

So don't do this:
funcdef myfunc(string s1, int number)

Do this:
typedef structure {
   string s1;
   int number;
} Params;
funcdef myfunc(Params p)

Asserting that the data matches a structure is fine, but that structure you are using to check does not match the spec (it has numeric values where you mark them as strings in the spec).

**Comment by realmarcin** [comment]
Excellent, thanks for the explanation.

**Comment by realmarcin** [comment]
re this: Asserting that the data matches a structure is fine, but that structure you are using to check does not match the spec (it has numeric values where you mark them as strings in the spec).

I fixed that this afternoon, there was a mismatch after the string conversion. The pushed code passed all tests.

**Comment by realmarcin** [comment]
re this: I still don't know what you mean by "the viewer requires a workspace name"

what I mean is that the workspace name and object id and name are fields that the UI viewer will be requesting (unless it can already know some of that otherwise).

**Comment by realmarcin** [comment]
aha, the workspace name is in the object info from get_objects -- so this is solved now. however, getting object info as a dict would really make life easier for everyone I think.

**Comment by realmarcin** [comment]
ok, looks like the finish line has been reached. I replaced the object ref with a struct with ref string and propagated those changes, including into the tests. all tests (including two more for direct by ref access) passed.

**Comment by msneddon** [comment]
I think we're getting closer, but I don't think we've crossed the line yet :)  And yes, sometimes it's difficult to communicate well with comments- I'm glad you see why we can pass the reference and should only need to make one service call...

But first, tests still don't pass for me!  You need to create any WS you plan to use on each test, otherwise it will never work for another developer.  Right now you're still hardcoded to use a WS named testReadsAPI: https://github.com/kbaseapps/ReadsAPI/blob/master/test/ReadsAPI_server_test.py#L146
Your test code already even has the function generated for you to create a WS for the tests, and the ContigFilter example shows you how to use it: https://github.com/kbaseapps/ReadsAPI/blob/master/test/ReadsAPI_server_test.py#L59-L66

Second, I'm not sure why you created a second function for getting each of the data items by reference rather than modifying the existing function.  There's nothing using this code yet, so there isn't any reason to keep it backwards compatible, and besides, adding a new field in the parameters input is backwards compatible.  Aside from making this a much more confusing and a difficult to understand API (which function should I use?  what are the differences? etc), on the backend it looks like the implementation code is just mostly duplicated, which will really make this code difficult to maintain and fix in the future.  Especially in this case, removing the duplication should be very easy by extracting the common code into a function.

Third, and I know I haven't brought this up yet, but the error handling is not very good.  You have try blocks in every function with a lot of code that catches all errors, not just errors coming from the Workspace, but then are simply rethrown with a new message stating they are WS errors.  So for instance, if there's just a 'key not found' or that type of error, you'll catch it and mask it as a workspace error.  This is worse than not catching any error, and just letting the exceptions propagate up.  If you're trying to catch WS errors, the code in the try block should only include the one line that makes the WS call, and you should catch the specific error type that is thrown from the client, not all errors.

**Comment by realmarcin** [comment]
1) Tests don't pass for you :( Could you pass along the error?
There is currently a warning and error if the test workspace already exists but the code recovers and continues. Perhaps that is what confused you?

2) All I did was convert the main methods to operate on parameter with ref and the original methods become wrappers which took in the ws name and object name etc, created the ref and passed along. There shouldn't be any duplicated code ... The methods are identical in return and simply allow users to access the same data with different input fields (ref vs object name etc), something that is quite common in APIs. Its easy to figure out what to use (and even easier with better docs) -- use the one for which you have inputs for. Eg from narrative its harder to get object ids so using object name is more natural. I can remove these methods and clean the spec but just wanted to make sure you knew the whole context.

3) OK, thanks -- I will look at more examples and spiff up the error handling.

**Comment by msneddon** [comment]
1) Sure, here is the error.  You're right that it detects if that workspace exists, but doesn't really recover- it seems to just fail:

```
======================================================================
ERROR: test_get_type_ok (ReadsAPI_server_test.ReadsAPITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ReadsAPI_server_test.py", line 110, in test_get_type_ok
    ws_obj_names = self.load_test_data_ok()
  File "ReadsAPI_server_test.py", line 166, in load_test_data_ok
    "provenance": summary_provenance}]})
  File "/kb/deployment/lib/biokbase/workspace/client.py", line 272, in save_objects
    [params], json_rpc_context)
  File "/kb/deployment/lib/biokbase/workspace/client.py", line 161, in _call
    raise ServerError(**err['error'])
ServerError: JSONRPCError: -32500. User wstester1 may not write to workspace testReadsAPI
us.kbase.workspace.exceptions.WorkspaceAuthorizationException: User wstester1 may not write to workspace testReadsAPI
    at us.kbase.workspace.database.Workspace.comparePermission(Workspace.java:157)
    at us.kbase.workspace.database.Workspace.comparePermission(Workspace.java:140)
    at us.kbase.workspace.database.Workspace.checkPermsMass(Workspace.java:216)
    at us.kbase.workspace.database.Workspace.checkPerms(Workspace.java:193)
    at us.kbase.workspace.database.Workspace.checkPerms(Workspace.java:180)
    at us.kbase.workspace.database.Workspace.saveObjects(Workspace.java:618)
    at us.kbase.workspace.kbase.WorkspaceServerMethods.saveObjects(WorkspaceServerMethods.java:309)
    at us.kbase.workspace.WorkspaceServer.saveObjects(WorkspaceServer.java:612)
    at sun.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at us.kbase.common.service.JsonServerServlet.processRpcCall(JsonServerServlet.java:595)
    at us.kbase.common.service.JsonServerServlet.doPost(JsonServerServlet.java:448)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:688)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
    at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1550)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:281)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
    at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:655)
    at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:595)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
    at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:331)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:231)
    at com.sun.enterprise.v3.services.impl.ContainerMapper$AdapterCallable.call(ContainerMapper.java:317)
    at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:195)
    at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:860)
    at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:757)
    at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1056)
    at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:229)
    at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
    at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
    at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
    at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
    at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
    at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
    at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
    at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
    at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
    at java.lang.Thread.run(Thread.java:745)


----------------------------------------------------------------------
Ran 9 tests in 1.996s

FAILED (errors=9)
make: *** [test] Error 1
Shutting down callback server...
1478546802.08 - CallbackServer: Shutting down executor service
```

2) Well- I can already tell that the API is confusing because I was looking at the wrong function :)   There are now 10 different functions that all have overlapping behavior - each of them just returns a different subset of "get_reads_info_all_by_ref" - they pretty much all call `get_objects2` or `get_object_info_new`, process the results by picking out some fields, and return that data.  The only difference, as far as I can tell, is what fields are returned and whether the query is by WS name and obj ID vs reference.  So the API would be significantly simplified by a single function that was parameterized.  For instance, imagine if instead of `get_objects2`, there were 10 different methods depending on the various combinations of inputs and what you wanted (eg with metadata returned or without, by ref or by WS name + obj id, just the type or the entire object Info, with provenance info or without).  More documentation doesn't actually help- it will still be confusing.  Instead, there is one function named `get_objects2` that is parameterized for the various special cases.  I think we should take the same strategy here and keep the total number of functions very low- maybe one to get metadata/ws info, and one to get everything, or even just one because the performance difference between the two will be minimal.

In regards to duplicating data, I did miss that you are reusing the `get_reads_info_all_by_ref` here: https://github.com/kbaseapps/ReadsAPI/blob/master/lib/ReadsAPI/ReadsAPIImpl.py#L384.  I was looking at `get_reads_info_by_ref` vs. `get_reads_info_all_by_ref`, but there is still a lot of duplicated code in this module.  For instance: https://github.com/kbaseapps/ReadsAPI/blob/master/lib/ReadsAPI/ReadsAPIImpl.py#L437-L454 is most of the implementation, and is pretty much identical to https://github.com/kbaseapps/ReadsAPI/blob/master/lib/ReadsAPI/ReadsAPIImpl.py#L527-L562, just with a different 'fields' array.

Already there is some confusion- there are commented out placeholders for 'strain' in one but not the other.  One day, if we want to add 'strain', it would be easy to forget to update the code in both places.  Duplicate code doesn't just mean exactly the same code, it also means things that are similar enough that they should be parameterized and factored out into a common function.  Since all the functions of this API do basically the same thing, there should be one place where they are implemented, even if the API still exposes multiple functions for whatever reason. Removing this type of duplication is what helps keep code maintainable and let's us make changes faster in the future.

3) great!

**Comment by realmarcin** [comment]
1) OK, regarding the WS failure that looks like a permissions issue. so the test workspace should be public?

**Comment by msneddon** [comment]
No, there shouldn't be anything that's public.  The tests should create a new private workspace every time and delete the workspace at the end.  It shouldn't assume any workspace with a particular name exists or can be created.  There's already a method generated for you to create a workspace and give you its name:  https://github.com/kbaseapps/ReadsAPI/blob/master/test/ReadsAPI_server_test.py#L59
Look again at the test example that's generated for you for filter_contigs.

So again, the point of doing this is so that the tests work for any test user against any endpoint, regardless of the particular state of CI/appdev/next etc.  So try running it with a different user, or against appdev, or even next.  It should work every time.  That way when tests fail, we can be reasonably certain a failure is due to code in this module, not due to missing test data or because a particular WS does or doesn't exist.

**Comment by msneddon** [comment]
It's looking better, but we've reached the next problem- tests still aren't passing for me because I don't have permissions to the shock node that is being referenced, which looks like it is also just assumed to be there.  Now that the ReadsUtils module has the updated uploader, you can import that client and use the ReadsUtils to create the test data.

```
======================================================================
ERROR: test_get_id_ok (ReadsAPI_server_test.ReadsAPITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ReadsAPI_server_test.py", line 79, in test_get_id_ok
    ws_obj_names = self.load_test_data_ok()
  File "ReadsAPI_server_test.py", line 171, in load_test_data_ok
    "provenance": summary_provenance}]})
  File "/kb/deployment/lib/biokbase/workspace/client.py", line 272, in save_objects
    [params], json_rpc_context)
  File "/kb/deployment/lib/biokbase/workspace/client.py", line 161, in _call
    raise ServerError(**err['error'])
ServerError: JSONRPCError: -32500. An error occured while processing IDs: The Handle Service reported that at least one of the handles contained in the objects in this call was not accessible with your credentials. The call cannot complete.
us.kbase.typedobj.exceptions.TypedObjectValidationException: An error occured while processing IDs: The Handle Service reported that at least one of the handles contained in the objects in this call was not accessible with your credentials. The call cannot complete.
    at us.kbase.workspace.database.Workspace.processIds(Workspace.java:808)
    at us.kbase.workspace.database.Workspace.saveObjects(Workspace.java:627)
    at us.kbase.workspace.kbase.WorkspaceServerMethods.saveObjects(WorkspaceServerMethods.java:309)
    at us.kbase.workspace.WorkspaceServer.saveObjects(WorkspaceServer.java:612)
    at sun.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
```

The exception handling is still not quite right.  Having the isolated try/except block around the WS call is better, but it is surrounded in another try/except block that will also catch your error.  You also still are catching all exceptions, not just specific ones that you might expect from the WS.  My opinion is that if you don't actually have anything to add to improve the error message, than you probably don't need to catch the errors at all.  Catching them only makes sense if you catch specific errors, give a better error message, or are able to recover from the error.  Otherwise you can let something else catch it outside of your function.
